local map = function(mode, keys, func, desc)
	vim.keymap.set(mode, keys, func, { desc = desc })
end

map("n", "<leader>sh", function()
	Snacks.picker.help()
end, "[S]earch [H]elp")
map("n", "<leader>sk", function()
	Snacks.picker.keymaps()
end, "[S]earch [K]eymaps")
map("n", "<leader>sf", function()
	Snacks.picker.files()
end, "[S]earch [F]iles")
map("n", "<leader>sw", function()
	Snacks.picker.grep_word()
end, "[S]earch current [W]ord")
map("n", "<leader>sg", function()
	Snacks.picker.grep()
end, "[S]earch by [G]rep")
map("n", "<leader>sd", function()
	Snacks.picker.diagnostics()
end, "[S]earch [D]iagnostics")
map("n", "<leader>sr", function()
	Snacks.picker.resume()
end, "[S]earch [R]esume")
map("n", "<leader>s.", function()
	Snacks.picker.recent()
end, '[S]earch Recent Files ("." for repeat)')
map("n", "<leader><leader>", function()
	Snacks.picker.buffers()
end, "[ ] Find existing buffers")
map("n", "<leader>st", function()
	Snacks.picker.todo_comments()
end, "[S]earch all [T]odo comments")
map("n", "<leader>sT", function()
	Snacks.picker.todo_comments({ keywords = { "TODO", "FIX", "FIXME" } })
end, "[S]earch only [T]odo/Fix/Fixme")
